# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_ussurl_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
