# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_ussurl_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
