# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20171209_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
